language: python
python:
  - "3.6"
script:
  - pytest

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install pytest-cov
  - pip install coveralls

before_script:
  flake8 app.py --select W,E722

# command to run tests
script:
  py.test --cov=app

after_success:
  - coverage report
  - coveralls