language: python
python:
  - "3.6"
script:
  - pytest

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov

# command to run tests
script:
  py.test --cov=app